apiVersion: v1
kind: Service
metadata:
  name: event-distribution-service
  namespace: event-review-platform
  labels:
    app: event-distribution-service
spec:
  type: ClusterIP
  selector:
    app: event-distribution-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000