apiVersion: v1
kind: Service
metadata:
  name: event-ingestor-service
  namespace: event-review-platform
  labels:
    app: event-ingestor-service
spec:
  type: ClusterIP
  selector:
    app: event-ingestor-service
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001